# Generated by Django 6.0.6 on 2026-07-02 18:54

import activities.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='activities.submission'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='uploaded_file',
            field=models.FileField(upload_to=activities.models.attachment_upload_path),
        ),
        migrations.AlterField(
            model_name='submissionfaculty',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_submissions', to='activities.faculty'),
        ),
        migrations.AlterField(
            model_name='submissionfaculty',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_members', to='activities.submission'),
        ),
    ]
