# Generated by Django 6.0.6 on 2026-07-07 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_submission_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('downloaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
