# Generated by Django 6.0.6 on 2026-07-09 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0005_reportdownload_user_submission_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
    ]
